<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-MSVEU0R" name="testngpack.Flag5" tests="3" failures="0" timestamp="2022-08-23T20:40:31 IST" time="0.008" errors="1">
  <testcase name="actiTimeLogin" time="0.007" classname="testngpack.Flag5">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testngpack.Flag5.actiTimeLogin(Flag5.java:9)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- actiTimeLogin -->
  <system-out/>
  <testcase name="actiTimeCreateUser" time="0.000" classname="testngpack.Flag5">
    <skipped/>
  </testcase> <!-- actiTimeCreateUser -->
  <system-out/>
  <testcase name="actiTimeLogout" time="0.001" classname="testngpack.Flag5"/>
  <system-out>
    <![CDATA[logout succesful]]>
  </system-out>
</testsuite> <!-- testngpack.Flag5 -->
